import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated byddcreate next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full py-4">
          <nav className="mx-auto max-w-3xl flex items-center justify-between px-6 text-sm">
            <a href="/" className="font-semibold hover:opacity-80">Gift</a>
            <a href="/celebrate" className="hover:opacity-80">Celebrate</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
